dialect "mvel"

import com.flowserve.system606.model.PerformanceObligation

rule "Calculate Percent Complete"
    when
        // Pull input values needed for calculation
        pob : PerformanceObligation(cumulativeCostIncurred : getCurrencyInput("CUMULATIVE_COST_INCURRED"), estimatedCostAtCompletion : getCurrencyInput("ESTIMATED_COST_AT_COMPLETION"))
    then
        // Execute calculation, set output
        pob.putCurrencyOutput("PERCENT_COMPLETE", cumulativeCostIncurred / estimatedCostAtCompletion);
end

rule "Calculate Revenue Earned to Date"
    when
        // Pull input values needed for calculation, one of which is an output from the previous calc.
        pob : PerformanceObligation(percentComplete : getCurrencyOutput("PERCENT_COMPLETE"), transactionPrice : getCurrencyInput("TRANSACTION_PRICE"))
    then
        // Execute calculation, set output
        pob.putCurrencyOutput("REVENUE_EARNED_TO_DATE", percentComplete * transactionPrice);
end


