package com.flowserve.system606.model;

/**
 * @author kgraves
 */
public enum InputTypeName {

    REVENUE_RECOGNITION_METHOD,
    ESTIMATED_COST_AT_COMPLETION,
    TRANSACTION_PRICE,
    LIQUIDATED_DAMAGES,
    CUMULATIVE_COST_INCURRED,
    CUMULATIVE_INTERCOMPANY_PROGRESS,
    CUMULATIVE_THIRD_PARTY_PROGRESS,
    DELIVERY_DATE,
    CUMULATIVE_COST_OF_GOODS_SOLD,
    BILLING_AMOUNT_CC,
    BILLING_AMOUNT_LC,
    BILLING_DATE,
    BILLING_INVOICE_NUMBER,
    REVENUE_START_DATE,
    REVENUE_END_DATE,
    TOTAL_TRANS_PRICE_CC,
    BOOKING_DATE,
    ESTIMATED_COMPLETION_DATE
}
