package com.flowserve.system606.model;

/**
 * @author kgraves
 */
public enum OutputTypeName {

    PERCENT_COMPLETE,
    REVENUE_EARNED_TO_DATE,
    ESTIMATED_GROSS_PROFIT,
    ESTIMATED_GROSS_MARGIN,
    CUMULATIVE_TOTAL_ITD_COSTS,
    CHANGE_IN_ESTIMATED_COST_AT_COMPLETION,
    CUMULATIVE_REVENUE_TO_RECOGNIZE,
    PERIOD_REVENUE,
    PERIOD_EX_RATE,
    PERIOD_REVENUE_LOCAL_CURRENCY,
    CUMULATIVE_REVENUE_LOCAL_CURRENCY,
    CUMULATIVE_LIQUIDATED_DAMAGES_CC,
    LIQUIDATED_DAMAGES_RECOGNIZE_CURRENT_PERIOD_CC,
    LIQUIDATED_DAMAGES_RECOGNIZE_CURRENT_PERIOD_LC,
    NET_PERIOD_SALES_LC,
    BACKLOG_REVALUED,
    TRANSACTION_PRICE_REVALUED,
    LIQUIDATED_DAMAGES_BACKLOG,
    LIQUIDATED_DAMAGES_BACKLOG_REVALUED_LC,
    LIQUIDATED_DAMAGES_RECOGNIZED_LC,
    TOTAL_ESTIMATED_LIQUIDATED_DAMAGES_LC,
    TOTAL_TRANSACTION_PRICE_NET_LIQUIDATED_DAMAGES_LC,
    COST_GOODS_SOLD_BACKLOG_REVALUED_LC,
    REMAINING_ESTIMATE_COMPLETE_LC,
    PROJECT_GAIN_LOSS_LC,
    ITD_STANDARD_COSTS_COGS,
    LOSS_CONTRACT_ADJUSTED,
    TOTAL_COST_GOODS_SOLD,

//    ESTIMATED_COST_AT_COMPLETION = "ESTIMATED_COST_AT_COMPLETION";
//    CUMULATIVE_COST_INCURRED = "CUMULATIVE_COST_INCURRED";
//    INTERCOMPANY_PROGRESS = "INTERCOMPANY_PROGRESS";
//    THIRD_PARTY_PROGRESS = "THIRD_PARTY_PROGRESS";
//    DELIVERY_DATE = "DELIVERY_DATE";
//    CUMULATIVE_COST_OF_GOODS_SOLD = "CUMULATIVE_COST_OF_GOODS_SOLD";
//    BILLING_AMOUNT_CONTRACT_CURRENCY = "BILLING_AMOUNT_CONTRACT_CURRENCY";
//    BILLING_AMOUNT_LOCAL_CURRENCY = "BILLING_AMOUNT_LOCAL_CURRENCY";
//    BILLING_DATE = "BILLING_DATE";
//    BILLING_INVOICE_NUMBER = "BILLING_INVOICE_NUMBER";
}
